**Data**

本賽題提供用戶在2016年1月1日至2016年5月31日之間真實線下消費行為，預測用戶在2016年6月領取優惠券後15天以內的使用情況。

**Evaluation**

本賽題目標是預測投放的優惠券是否在規定時間內核銷。針對此任務及一些相關背景知識，以該用戶使用於某日取得之優惠券核銷預測 AUC（ROC 曲線下面積）作為評價標準。即對將 User_id - Date_received - Coupon_id 為一組計算核銷預測的AUC值，若某使用者於同一日取得多張相同優惠券，則任一張核銷皆為有效核銷。

In [1]:
import os
import numpy as np  # useful for many scientific computing in Python
import pandas as pd # primary data structure library
import matplotlib.pyplot as plt
import datetime as dt
import seaborn as sns
import matplotlib as mpl
%matplotlib inline
sns.set_style(None,{"font.sans-serif":['simhei', 'Arial']})

pd.set_option('display.max_columns', 500)

import warnings
warnings.filterwarnings('ignore')
plt.style.use('ggplot')

In [2]:
data = pd.read_csv('/Users/yichingchan/Documents/2nd-ML100Days/ml100marathon-02-01/train_offline.csv')

In [3]:
def status(row):
    receive = row['Date_received']
    buy = row['Date']
    if receive != None & buy == None:
        return 0
    elif receive

,User_id,Merchant_id,Coupon_id,Discount_rate,Distance,Date_received,Date
0,1439408,2632,NaN,NaN,0.0,NaN,20160217.0
1,1439408,2632,8591.0,20:1,0.0,20160217.0,NaN
2,1439408,2632,1078.0,20:1,0.0,20160319.0,NaN
3,1832624,3381,7610.0,200:20,0.0,20160429.0,NaN
4,2029232,3381,11951.0,200:20,1.0,20160129.0,NaN
5,2223968,3381,9776.0,10:5,2.0,20160129.0,NaN
6,73611,2099,12034.0,100:10,NaN,20160207.0,NaN
7,163606,1569,5054.0,200:30,10.0,20160421.0,NaN
8,3273056,4833,7802.0,200:20,10.0,20160130.0,NaN
9,94107,3381,7610.0,200:20,2.0,20160412.0,NaN
10,253750,8390,NaN,NaN,0.0,NaN,20160327.0
11,253750,8390,7531.0,20:5,0.0,20160327.0,NaN
12,376492,1041,13490.0,30:5,2.0,20160127.0,NaN
13,1964720,7884,NaN,NaN,10.0,NaN,20160115.0
14,1964720,7884,6704.0,20:1,10.0,20160215.0,NaN
15,1113008,1041,NaN,NaN,2.0,NaN,20160114.0
16,1113008,1041,11197.0,30:5,2.0,20160114.0,NaN
17,2881376,5341,111.0,30:5,1.0,20160207.0,NaN
18,2881376,8390,7531.0,20:5,0.0,20160321.0,20160329.0
19,2881376,5341,111.0,30:5,1.0,20160207.0,NaN
20,2881376,8390,NaN,NaN,0.0,NaN,20160321.0
21,4061024,2709,2840.0,100:10,10.0,20160129.0,NaN
22,4061024,3381,7610.0,200:20,10.0,20160426.0,NaN
23,4061024,7555,9871.0,30:5,10.0,20160409.0,NaN
24,4061024,3381,9776.0,10:5,10.0,20160129.0,NaN
25,7073472,2934,NaN,NaN,0.0,NaN,20160322.0
26,7073472,3381,7610.0,200:20,0.0,20160326.0,NaN
27,7073472,2934,5686.0,30:5,0.0,20160322.0,NaN
28,7073472,6485,9407.0,100:10,0.0,20160130.0,NaN
29,7073472,2934,5686.0,30:5,0.0,20160322.0,NaN
...,...,...,...,...,...,...,...
1160712,3400544,3485,NaN,NaN,0.0,NaN,20160414.0
1160713,3400544,6454,14031.0,100:10,2.0,20160131.0,NaN
1160714,3400544,3485,NaN,NaN,0.0,NaN,20160115.0
1160715,457900,7907,13118.0,150:30,NaN,20160418.0,NaN
1160716,2876768,6901,NaN,NaN,0.0,NaN,20160421.0
1160717,179830,3381,1807.0,300:30,0.0,20160124.0,NaN
1160718,179830,4059,7166.0,100:10,7.0,20160124.0,NaN
1160719,179830,6434,10050.0,50:5,1.0,20160123.0,NaN
1160720,179830,6284,4567.0,50:10,1.0,20160124.0,NaN
1160721,179830,6284,7379.0,50:10,1.0,20160124.0,NaN
1160722,179830,3710,13056.0,150:10,4.0,20160124.0,NaN
1160723,179830,2099,12034.0,100:10,1.0,20160124.0,NaN
1160724,179830,4660,1480.0,100:10,0.0,20160125.0,NaN
1160725,179830,5341,7751.0,50:10,0.0,20160123.0,NaN
1160726,179830,7555,17.0,30:5,7.0,20160123.0,NaN
1160727,179830,760,3237.0,20:5,0.0,20160124.0,NaN
1160728,179830,2099,12034.0,100:10,1.0,20160203.0,NaN
1160729,343276,4206,NaN,NaN,5.0,NaN,20160425.0
1160730,653784,195,NaN,NaN,0.0,NaN,20160418.0
1160731,653784,195,NaN,NaN,0.0,NaN,20160416.0
1160732,3795296,5341,111.0,30:5,0.0,20160129.0,NaN
1160733,188086,6568,NaN,NaN,0.0,NaN,20160415.0
1160734,188086,6568,4723.0,30:1,0.0,20160415.0,NaN
1160735,188086,6568,NaN,NaN,0.0,NaN,20160417.0
1160736,212662,3532,NaN,NaN,1.0,NaN,20160308.0
1160737,212662,2934,5686.0,30:5,2.0,20160321.0,20160330.0
1160738,212662,3532,5267.0,30:5,1.0,20160322.0,NaN
1160739,212662,2934,5686.0,30:5,2.0,20160321.0,20160322.0
1160740,212662,3532,NaN,NaN,1.0,NaN,20160322.0
1160741,212662,2934,NaN,NaN,2.0,NaN,20160321.0